### ISSUE TITLE
Compilation error after dependencies update

### ISSUE THREAD

**Issue by palevi67** [davrux/go-smtptester#1]
Here is the output ...

github.com\davrux\go-smtptester@v1.0.0\server.go:52:9: cannot use newSession(bkd) (value of type *Session) as smtp.Session value in return statement: *Session does not implement smtp.Session (wrong type for method Rcpt)
		have Rcpt(string) error
		want Rcpt(string, *smtp.RcptOptions) error
FAIL	github.com/horus-es/go-util/v2/plantillas [build failed]
FAIL

![error](https://github.com/davrux/go-smtptester/assets/3084095/ac43bfc3-0828-4adb-bf30-e0c4f4a1aa50)

**Comment by palevi67** [comment]
I have solved it by enforcing an outdated version of go-smtp:

	github.com/emersion/go-smtp v0.17.0 // indirect

**Comment by choopm** [comment]
```
# github.com/davrux/go-smtptester
/go/pkg/mod/github.com/davrux/go-smtptester@v1.0.0/server.go:52:9: cannot use newSession(bkd) (value of type *Session) as smtp.Session value in return statement: *Session does not implement smtp.Session (wrong type for method Rcpt)
                have Rcpt(string) error
                want Rcpt(string, *smtp.RcptOptions) error
FAIL    github.com/xxx/xxx/internal/broker [build failed]
```
